name: "Reset Database"

on:
  workflow_run:
    workflows: ["Pull Request Deploy"]
    types:
      - completed

jobs:
  reset_database:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: show environment variables
        run: |
          echo "reset_database"
          echo $(printenv)
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo '${{ env.GITHUB_CONTEXT }}'
          echo 'event_name'
          echo '${{ github.event_name }}'
          echo 'workflow_run event'
          echo '${{ github.event.workflow_run.event }}'
          echo 'event.workflow_run.pull_requests[0].number'
          echo '${{ github.event.workflow_run.pull_requests[0].number }}'
          echo 'event.workflow_run.pull_requests[0].head.ref'
          echo '${{ github.event.workflow_run.pull_requests[0].head.ref }}'