name: "Release Production"

on:
  release:
    types: [released]

jobs:
  release:
    name: "Release to production"
    runs-on: "ubuntu-latest"
    concurrency: release-production

    steps:
      - uses: actions/checkout@v2

      - name: Create preview env file
        run: |
          echo "release to production"
    
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
